### ISSUE TITLE
Merge Board Fails to start

### ISSUE THREAD

**Issue by MystiaTech** [bbc-mc/sdweb-merge-board#16]
I recently updated my A111's webui (01/28/2023) and I noticed this errror. I made sure that the extension was up to date and it still at an issue.

```
Error executing callback ui_tabs_callback for E:\Downloads\stable-diffusion-webui\extensions\sdweb-merge-board\scripts\merge_board.py
Traceback (most recent call last):
  File "E:\Downloads\stable-diffusion-webui\modules\script_callbacks.py", line 106, in ui_tabs_callback
    res += c.callback() or []
  File "E:\Downloads\stable-diffusion-webui\extensions\sdweb-merge-board\scripts\merge_board.py", line 29, in on_ui_tabs
    btn_run_merge, btn_reload_checkpoints, btn_send_to_recipe, submit_result, btn_clear_merge_settings, \
ValueError: not enough values to unpack (expected 88, got 86)
```

I love this extension because it makes mixing models so much easier.

**Comment by bbc-mc** [comment]
Hi, thank you for report.

At first, try `Restart whole A1111 Web UI`.
There is sometimes UI update in my extension update, it causes such error if you only try "Apply and Restart UI" button from A1111 settings menu.

`(expected 88, got 86)` means you update from version before  "Skip merge if same name checkpoint already exists" on Dec 13,
and now this function have 88 params.
So this message means `ui_merge.py` is not correctly loaded (stay old, with 86 params) on memory or cache.

**Comment by MystiaTech** [comment]
I'll give it an attempt again but I did do a few apply and reloads to fix an issue with another extension and I was still seeing this error. I'll try a full reboot of the software and follow up
